on: [push, pull_request]
name: Lint
jobs:
  build:
    runs-on: ubuntu-latest

    name: Lint

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x

      - name: Print deno version
        run: deno --version

      - name: Format
        run: deno fmt --check **/*.ts

      - name: Lint
        run: deno lint --unstable
