on:
  push:
    paths:
      - '**.ts'
name: Test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [1.3, 1.x]
        os: [macOS-latest, ubuntu-latest, windows-2019]
    name: Test with Deno ${{ matrix.deno }}  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write --location=http://localhost:1357
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x

      - name: Print deno version
        run: deno --version

      - name: Format
        run: deno fmt --check **/*.ts

      - name: Lint
        run: deno lint --unstable **/*.ts
