on: [push, pull_request]
name: Test
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [1.3, 1.4, 1.5, 1.6, 1.x]
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write
  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        deno: [1.3, 1.x]
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write
  test-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        deno: [1.3, 1.x]
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write
