on: [push, pull_request]
name: Test
jobs:
  test-ubuntu:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [1.3, 1.4, 1.5, 1.6, 1.x, ]
        os: [macOS-latest, ubuntu-latest, windows-2019]
    name: Test with Deno ${{ matrix.deno }}  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write
